# Generated by Django 5.0.4 on 2024-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_poster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
